-- ===========================================================================
-- Munch — Supabase schema
--
-- Already applied to the Munch project as migration `munch_records`. Kept here so
-- the schema is reviewable alongside the code, and so a second project can be set
-- up by pasting this into the SQL editor. Safe to run again; every statement
-- guards itself.
--
-- Scoping each policy `to authenticated` means the anon role matches no policy at
-- all, so a request holding only the publishable key sees nothing. Verified on
-- this project: own rows readable, cross-user writes refused, other users and
-- anonymous callers both see zero rows.
--
-- Design note: one generic record table rather than a table per collection.
-- The app syncs last-write-wins per record, so what it needs from the database
-- is a keyed bag of documents it can pull incrementally. That gives per-item
-- merging — two devices editing different items both keep their edit — without
-- a table and a mapping layer for each of stock, meals, list, aisles and
-- settings.
-- ===========================================================================

create table if not exists public.munch_records (
  user_id    uuid        not null references auth.users (id) on delete cascade,

  -- Which collection the record belongs to. 'slot' is one meal on one day,
  -- 'tick' is a ticked-off shopping line, 'setting' is the single settings blob.
  kind       text        not null,

  -- Stable id within the collection, generated by the client.
  id         text        not null,

  -- The record itself. Null together with a deleted_at means a tombstone: the
  -- client needs to hear about deletions, so rows are never hard-deleted.
  payload    jsonb,

  -- Client clock, and the only thing that decides which of two competing edits
  -- wins. Devices with badly wrong clocks will therefore win or lose unfairly;
  -- for a single person's food data that trade is worth the simplicity.
  updated_at timestamptz not null,

  -- Server clock, maintained by the trigger below. Incremental pulls filter on
  -- this rather than updated_at so that a skewed client clock cannot cause a
  -- device to silently skip records.
  synced_at  timestamptz not null default now(),

  deleted_at timestamptz,

  primary key (user_id, kind, id),
  constraint munch_records_kind_check check (
    kind in ('inventory', 'slot', 'shopping', 'library', 'location', 'setting', 'tick')
  )
);

-- The only query pattern: everything of mine the server has seen since X.
create index if not exists munch_records_pull_idx
  on public.munch_records (user_id, synced_at);

-- --- server clock ----------------------------------------------------------

create or replace function public.munch_touch_synced_at()
returns trigger
language plpgsql
set search_path = ''      -- so the function cannot be hijacked via search_path
as $$
begin
  new.synced_at := now();
  return new;
end;
$$;

drop trigger if exists munch_records_synced_at on public.munch_records;
create trigger munch_records_synced_at
  before insert or update on public.munch_records
  for each row execute function public.munch_touch_synced_at();

-- --- row-level security ----------------------------------------------------
--
-- This is what makes it safe to publish the anon key in a static site. Without
-- these policies enabled, that key would let anyone read and overwrite the
-- table. Every policy is scoped to the signed-in user, so a request carrying
-- someone's JWT can only ever see that person's rows.

alter table public.munch_records enable row level security;

drop policy if exists munch_records_select on public.munch_records;
create policy munch_records_select on public.munch_records
  for select to authenticated using ((select auth.uid()) = user_id);

drop policy if exists munch_records_insert on public.munch_records;
create policy munch_records_insert on public.munch_records
  for insert to authenticated with check ((select auth.uid()) = user_id);

drop policy if exists munch_records_update on public.munch_records;
create policy munch_records_update on public.munch_records
  for update to authenticated using ((select auth.uid()) = user_id)
  with check ((select auth.uid()) = user_id);

-- No delete policy on purpose. The client tombstones instead of deleting, so
-- nothing needs the right to remove a row, and an account cannot lose history
-- to a bug. Cascade from auth.users still cleans up if the account is deleted.

-- ===========================================================================
-- After running this, two more things in the dashboard:
--
-- 1. Authentication → URL Configuration → Redirect URLs
--    Add your site, or the magic link will refuse to come back to it:
--        https://<owner>.github.io/munch/
--    Add http://127.0.0.1:8765/ too if you want sign-in to work locally.
--
-- 2. Project Settings → API
--    Already done for the Munch project — js/config.js holds its URL and
--    publishable key. Both are safe to commit; the policies above are what keep
--    the data private. Never put the service_role key in this repo: it bypasses
--    every policy here.
-- ===========================================================================
